databases:
  -
    database: fec_linker
    username: root
    password: ''
    host: localhost
    linkable_tables:
      -
        table: individual_contributions_2014
        id: id
        individual_id: individual_id
        full_name: contributor_name
        first_name:
        middle_name:
        last_name:
        city: city
        state: state
        zipcode: zipcode
        employer: employer
        occupation: occupation

individuals:
  database: fec_linker
  table_name: individuals
  id: id
  full_name: full_name
  first_name: first_name
  middle_name: middle_name
  last_name: last_name
  city: city
  state: state
  zipcode: zipcode
  employer: employer
  occupation: occupation

possibles:
  database: fec_linker
  table_name: individual_possible_matches
